/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.io.File;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class menu_utama extends javax.swing.JFrame {

    public final Connection conn = new koneksi().connect();

    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new tampilan.backgroundmenuutama();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnDataBarang = new javax.swing.JMenuItem();
        btnDataSupplier = new javax.swing.JMenuItem();
        btnDataKategori = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnTransaksi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        laporanStokBarang = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        laporanDataSupplier = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        jMenu1.setText("Aksi");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(btnLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data");

        btnDataBarang.setText("Data Barang");
        btnDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBarangActionPerformed(evt);
            }
        });
        jMenu2.add(btnDataBarang);

        btnDataSupplier.setText("Data Supplier");
        btnDataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSupplierActionPerformed(evt);
            }
        });
        jMenu2.add(btnDataSupplier);

        btnDataKategori.setText("Data Kategori");
        btnDataKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataKategoriActionPerformed(evt);
            }
        });
        jMenu2.add(btnDataKategori);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jMenu3.add(btnTransaksi);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");

        laporanStokBarang.setText("Laporan Stok Barang");
        laporanStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanStokBarangActionPerformed(evt);
            }
        });
        jMenu4.add(laporanStokBarang);

        jMenuItem6.setText("Laporan Transaksi");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        laporanDataSupplier.setText("Laporan Data Supplier");
        laporanDataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanDataSupplierActionPerformed(evt);
            }
        });
        jMenu4.add(laporanDataSupplier);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("CSV");

        jMenuItem1.setText("CSV Barang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("CSV Supplier");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBarangActionPerformed
        data_barang data_barang = new data_barang(this, rootPaneCheckingEnabled);
        data_barang.setLocationRelativeTo(this);
        data_barang.setVisible(true);

//        data_barang data_barang = new data_barang(this, rootPaneCheckingEnabled);
//        data_barang.setLocationRelativeTo(this);
//        data_barang.setVisible(true);
    }//GEN-LAST:event_btnDataBarangActionPerformed

    private void btnDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSupplierActionPerformed
        data_supplier data_supplier = new data_supplier(this, rootPaneCheckingEnabled); //this = menu utama
        data_supplier.setLocationRelativeTo(this);
        data_supplier.setVisible(true);
    }//GEN-LAST:event_btnDataSupplierActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        transaksi_bm data_bm = new transaksi_bm(this, rootPaneCheckingEnabled); //this = menu utama
        data_bm.setLocationRelativeTo(this);
        data_bm.setVisible(true);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnDataKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataKategoriActionPerformed
        data_kategori data_kategori = new data_kategori(this, rootPaneCheckingEnabled); //this = menu utama
        data_kategori.setLocationRelativeTo(this);
        data_kategori.setVisible(true);
    }//GEN-LAST:event_btnDataKategoriActionPerformed

    private void laporanStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanStokBarangActionPerformed
        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            conn = DriverManager.getConnection("jdbc::mysql://localhost/db_coba", "root", "");
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\TR_CRUD_REPORT_PRESENTASIII_KURANGFIX\\src\\laporan\\report2.jrxml");
            String query = "SELECT * FROM tb_barang";
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jdesign.setQuery(updateQuery);
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null, conn);
//            JasperViewer.viewReport(jprint);
            JasperViewer jasperviewer = new JasperViewer(jprint, false);
            jasperviewer.setVisible(true);
            //modalitytype null
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(tesreport.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(tesreport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
//            Logger.getLogger(laporandatabarang.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "gagal buka laporan" + ex);
        }
    }//GEN-LAST:event_laporanStokBarangActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        String yatidak[] = {"IYA", "TIDAK"};
        int pilihan = JOptionPane.showOptionDialog(null, "Apakah anda yakin ingin logout?", "Peringatan", JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, yatidak, yatidak[1]);
        if (pilihan == 0) {
            login masuk = new login();
//            masuk.setLocationRelativeTo(null);
            masuk.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void laporanDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanDataSupplierActionPerformed
        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            conn = DriverManager.getConnection("jdbc::mysql://localhost/db_coba", "root", "");
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\TR_CRUD_REPORT_PRESENTASIII_KURANGFIX\\src\\laporan\\report1.jrxml");
            String query = "SELECT * FROM tb_supplier";
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jdesign.setQuery(updateQuery);
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null, conn);
//            JasperViewer.viewReport(jprint);
            JasperViewer jasperviewer = new JasperViewer(jprint, false);
            jasperviewer.setVisible(true);
            //modalitytype null
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(tesreport.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(tesreport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
//            Logger.getLogger(laporandatabarang.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "gagal buka laporan" + ex);
        }
    }//GEN-LAST:event_laporanDataSupplierActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            PrintWriter pw = new PrintWriter(new File("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\TR_CRUD_REPORT_PRESENTASIII_KURANGFIX\\csv\\tb_barang.csv"));
            StringBuilder sb = new StringBuilder();

            ResultSet rs = null;

            String query = "select * from tb_barang";
            PreparedStatement ps = conn.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {
                sb.append(rs.getString("id_barang"));
                sb.append(",");
                sb.append(rs.getString("kode_barang"));
                sb.append(",");
                sb.append(rs.getString("nama_barang"));
                sb.append(",");
                sb.append(rs.getString("kode_kategori"));
                sb.append(",");
                sb.append(rs.getString("jumlah_barang"));
                sb.append("\r\n");
            }

            pw.write(sb.toString());
            pw.close();
            JOptionPane.showMessageDialog(null, "Berhasi buat csv barang");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal buat csv" + e);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            PrintWriter pw = new PrintWriter(new File("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\TR_CRUD_REPORT_PRESENTASIII_KURANGFIX\\csv\\tb_supplier.csv"));
            StringBuilder sb = new StringBuilder();

            ResultSet rs = null;

            String query = "select * from tb_supplier";
            PreparedStatement ps = conn.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {
                sb.append(rs.getString("id_supplier"));
                sb.append(",");
                sb.append(rs.getString("kode_supplier"));
                sb.append(",");
                sb.append(rs.getString("nama_supplier"));
                sb.append("\r\n");
            }

            pw.write(sb.toString());
            pw.close();
            JOptionPane.showMessageDialog(null, "Berhasi buat csv supplier");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal buat csv" + e);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnDataBarang;
    private javax.swing.JMenuItem btnDataKategori;
    private javax.swing.JMenuItem btnDataSupplier;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JMenuItem btnTransaksi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem laporanDataSupplier;
    private javax.swing.JMenuItem laporanStokBarang;
    // End of variables declaration//GEN-END:variables
}
